schema-version: v1
kind: plugin
metadata:
  name: plugin-infra-example
  display-name: plugin-infra-example
  description: Esse plugin utiliza o máximo de recursos possíveis de plugins para gerar um exemplo completo na publicação, exibição e utilização.
  version: 1.0.1
  picture: plugin.png
spec:
  type: infra
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-1.0.0.md
  requirements: docs/requirements.md
  repository: https://github.com/fabianofernandeszup/plugin-infra-example.git
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  requires:
    connection-interface:
      - aws-rds-conn
  generates:
    connection-interface:
      - aws-vpc-conn
  inputs-envs:
    - label: Input Env text com required true sem valor default
      name: resourceenv1
      type: text
      required: true

    - label: Input Env text com required false sem valor default
      name: resourceenv2
      type: text
      required: false

    - label: Input Env text com required true sem valor default
      name: resourceEnv3
      type: text
      required: true

    - label: Input Env text com required false sem valor default
      name: resourceenv3
      type: text
      required: false

  inputs:
    - label: Input text com pattern regex, required true e Help
      name: resource1
      type: text
      required: true
      default: Client
      pattern: '([A-Z][a-z]+)+'
      help: 'Inform your resource name (e.g.: Client)'

    - label: Input text com required true sem valor default
      name: resource2
      type: text
      required: true

    - label: Input text com required false sem valor default
      name: resource3
      type: text
      required: false

    - label: Input text sem tag required (Deve ser obrigatório) sem valor default
      name: resource4
      type: text

    - label: Input text sem tag required com valor default (Client)
      name: resource4
      type: text
      default: Client

    - label: Input text com tag required true e com valor default (Client)
      name: resource5
      type: text
      default: Client
      required: false

    - label: Input text com itens sem valor default required true
      name: method1
      type: text
      items:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      required: true

    - label: Input text com itens com 1 valor default (POST) required true
      name: method2
      type: text
      items:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      default: POST
      required: true

    - label: Input text com itens sem valor default required false
      name: method4
      type: text
      items:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      default: GET
      required: false

    - label: Input text com itens com 1 valor default (POST) required false
      name: method5
      type: text
      items:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      default: POST
      required: false

    # Bug no CLI de lista só com 1 Item
    - label: Input text com 1 item e sem valor default e required true
      name: method7
      type: text
      items:
        - GET
      default: GET
      required: true

    - label: Input text com 1 item e sem valor default e required false
      name: method9
      type: text
      items:
        - GET
      default: GET
      required: false

    - label: Input password required true
      name: password1
      type: password
      required: true

    - label: Input password required false
      name: password2
      type: password
      required: false

    - label: (Input text com itens) Qual linguagem deseja usar?
      type: text
      name: language
      items:
        - Java
        - Kotlin
        - Node

    - label: (Condicional do input language==Java) Qual versão do Java deseja usar?
      type: text
      name: java_version
      items:
        - "11"
        - "17"
      condition:
        variable: language
        operator: "=="
        value: Java

    - label: (Condicional do input language==Kotlin) Qual versão do Kotlin deseja usar?
      type: text
      name: kotlin_version
      items:
        - "1.6"
        - "1.7"
      condition:
        variable: language
        operator: "=="
        value: Kotlin

    - label: (Input select) Qual VM deseja usar ?
      type: select
      name: vm
      items:
        - "JVM"
        - "GraalVM"
      condition:
        variable: language
        operator: "containsAny"
        value: [Java,Kotlin]

    - label: (Input multiselect required true sem valor default) Qual porta deseja expor ?
      type: multiselect
      name: port1
      items:
        - "8080"
        - "8888"
      required: true

    - label: (Input multiselect required false sem valor default) Qual porta deseja expor ?
      type: multiselect
      name: port2
      items:
        - "8080"
        - "8888"
      required: false

    - label: (Input multiselect required true com 1 valor default) Qual porta deseja expor ?
      type: multiselect
      name: port3
      items:
        - "8080"
        - "8888"
      default: ["8888"]
      required: true

    - label: (Input multiselect required false com 1 valor default) Qual porta deseja expor ?
      type: multiselect
      name: port4
      items:
        - "8080"
        - "8888"
      default: ["8888"]
      required: false

    - label: (Input multiselect required true com 2 valores default) Qual porta deseja expor ?
      type: multiselect
      name: port5
      items:
        - "8080"
        - "8888"
      default: ["8080","8888"]
      required: true

    - label: (Input multiselect required false com 2 valores default) Qual porta deseja expor ?
      type: multiselect
      name: port6
      items:
        - "8080"
        - "8888"
      default: ["8080","8888"]
      required: false

    - label: (Input Select) Selecione um dominio
      type: select
      name: domain1
      items:
        - "*.com"
        - "*.com.br"

    # Bug com lista com 1 item
    - label: (Input Select com 1 item) Selecione um dominio
      type: select
      name: domain2
      items:
        - "*.com"

  global-computed-inputs:
    name_formatted_global: "{{ resource1 | upper }}"
  computed-inputs:
    name_formatted: "{{ resource1 | upper }}"
  hooks:
    - type: run
      trigger: before-input
      commands:
        - echo plugin before-input!
    - type: run
      trigger: before-render
      commands:
        - echo plugin before-render
    - type: run
      trigger: after-render
      commands:
        - echo plugin after-render!